version: "3.8"
services:
  weather_postgres:
    image: postgres:latest
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  weather_backend:
    depends_on:
      - weather_postgres
    build:
      dockerfile: Dockerfile 
      context: .
    environment:
      DATABASE_URL: postgres://user:password@weather_postgres:5432/postgres
    ports: 
      - "3000:3000"
volumes:
  pgdata: